### ISSUE TITLE
Immersive froze when i chose a definition for exporting a card

### ISSUE THREAD

**Issue by chris677** [Ben-Kerman/immersive#1]
Info that might help:using an italian dictionary in the migaku dictionary format 
![fD4BKOKZd7](https://user-images.githubusercontent.com/55905872/103439698-4a934100-4c93-11eb-85f4-cf39033f66a9.jpg)

**Comment by Ben-Kerman** [comment]
Should be fixed by d98e520019b22dfea1094d5dd6b21d746ab5a72e
