### ISSUE TITLE
Please include comparison with mpvacious

### ISSUE THREAD

**Issue by skangas** [Ben-Kerman/immersive#10]
Please consider including a comparison with [mpvacios](https://github.com/Ajatt-Tools/mpvacious) in the README. That seems to be the script used my Matt in his videos on mpv and I can't understand why this is a separate project. Thanks!

**Comment by Ben-Kerman** [comment]
It should be fairly obvious what the main difference is if you read the readme, since mpvacious' manual doesn't mention dictionary lookups or adding definitions anywhere (aside from telling you to do it with an external program). Anyway, here's a comparison I wrote a while back, it still applies to 1.2, the upcoming version of Immersive has even more features:

> The biggest difference is that Immersive has integrated dictionary support while mpvacious needs something external like Yomichan or the Migaku addon (which doesn't mean you couldn't use those with my script if you wanted to). You can look up words and add dictionary definitions to your cards directly from mpv, without switching to another window. It also has a better interface and just more features in general. Some smaller features (aside from dictionary support) that Immersive has but afaik mpvacious doesn't:
> - Select Forvo audio clips instead of always using the first one
> - Multiple Anki targets, so you can create cards in different decks and with different note types
> - Copy individual words from subtitles
> - Preview audio before creating a card
> - Customizable key bindings

In the end the core functionality is very similar, I just didn't like the way some things work with mpvacious and wanted to do a few things mpvacious couldn't, so I wrote a new script. I think once you have it set up Immersive has a better interface and is much easier to use (and more versatile), though.

**Comment by skangas** [comment]
> It should be fairly obvious what the main difference is if you read the readme, since mpvacious' manual doesn't mention dictionary lookups or adding definitions anywhere (aside from telling you to do it with an external program). Anyway, here's a comparison I wrote a while back, it still applies to 1.2, the upcoming version of Immersive has even more features:
>
> > The biggest difference is that Immersive has integrated dictionary support while mpvacious needs something external like Yomichan or the Migaku addon (which doesn't mean you couldn't use those with my script if you wanted to). You can look up words and add dictionary definitions to your cards directly from mpv, without switching to another window. It also has a better interface and just more features in general. Some smaller features (aside from dictionary support) that Immersive has but afaik mpvacious doesn't:
> > 
> > * Select Forvo audio clips instead of always using the first one
> > * Multiple Anki targets, so you can create cards in different decks and with different note types
> > * Copy individual words from subtitles
> > * Preview audio before creating a card
> > * Customizable key bindings
> 
> In the end the core functionality is very similar, I just didn't like the way some things work with mpvacious and wanted to do a few things mpvacious couldn't, so I wrote a new script. I think once you have it set up Immersive has a better interface and is much easier to use (and more versatile), though.

Thanks. It wasn't obvious for me to figure out all the above from reading the README, no. I would suggest you add the above comparison to the README for the benefit of others.
