### ISSUE TITLE
Migaku dictionary: Ability to use selected target word for "word" field, rather than the terms in the dictionary

### ISSUE THREAD

**Issue by 1over137** [Ben-Kerman/immersive#11]
I am using this script for making Russian sentence cards. I'm using Vicon dictionary which is in the Migaku format. However, when I use it to look up a word, the term displayed on screen and exported is often not in the form desired. It is neither in the dictionary form, or the way I selected it. Instead, it appears to be the first matching entry in the dictionary. Is there a way to change this?

**Comment by Ben-Kerman** [comment]
I just implemented a solution for this, sorry it took it so long. If you use the most recent commit (a5fb852), you can now include the original selected text in a field template like this: `{{selections[1]}}`, or `{{selections:::, }}` for multiple words separated by commas. Feel free to reopen the issue or create a new one if there are any issues
