### ISSUE TITLE
Amazing Script in theory, But It keeps creating Empty Anki cards with "placeholder"

### ISSUE THREAD

**Issue by abadyaaa** [Ben-Kerman/immersive#13]
Thanks to Ben for creating this Phenomenal Script, But after uncountable times of reinstalling and trying to debug it myself but I couldn't solve the issue.

![image](https://user-images.githubusercontent.com/61440536/124001013-d7b61900-d9dc-11eb-8d64-604a71a8b1e7.png)
everything works with me Just like in the demo, but when I click "f" to export the card it says " note added successfully" But in fact, it did not :
![image](https://user-images.githubusercontent.com/61440536/124001448-514e0700-d9dd-11eb-9d14-9240630d33b2.png)

and the created card look like this in Anki :
![image](https://user-images.githubusercontent.com/61440536/124001578-73e02000-d9dd-11eb-9037-893c971c2897.png)
.

Thanks, Ben for Programming this masterpiece of a script, But please help me use this Script, Because I know it will change my process of language learning for Good.

Also, I'm willing to help with any other info about the issue from my end, and anything else!!...

**Comment by Ben-Kerman** [comment]
I guess you didn't set up your note type's fields in the target config, or forgot to uncomment the relevant lines. It should look something like this (with the field names of your note type, of course):
```
field:Sentence={{sentences}}
field:Definition={{definitions}}
field:Audio={{audio}}
field:Image={{image}}
```

**Comment by abadyaaa** [comment]
Hey Ben, thanks for your fast response, man💜.

I did try to set up the field names so many times, but it didn't work so I kept it like it is in the target config, and made the Anki field names like the Default names in the Target config, I recorded the setup for you in a short 2 minutes video: https://youtu.be/lGYvW4OUXgM

**Comment by Ben-Kerman** [comment]
You need to remove the `#` at the start of the field definitions

**Comment by abadyaaa** [comment]
Hey Ben, thanks for your fast response, man💜.

I did try to set up the field names so many times, but it didn't work so I kept it like it is in the target config, and made the Anki field names like the Default names in the Target config, I recorded the setup for you in a short 2 minutes video: https://youtu.be/lGYvW4OUXgM

as you can see, I did everything as you advised (I guess🙄), Hope it's fixable. 
and thanks for your time buddy 💜.

**Comment by abadyaaa** [comment]
> You need to remove the `#` at the start of the field definitions
It worked like a charm.
YOU ARE A LEGEND, MY FRIEND 🙂🔥.
