### ISSUE TITLE
Error: attempt to perform arithmetic on field 'start' (a nil value) when trying to export

### ISSUE THREAD

**Issue by pndyjack** [Ben-Kerman/immersive#4]
![mpv_aW1fWqgXCk](https://user-images.githubusercontent.com/20967911/106341726-2cbafb00-6296-11eb-8203-cd3ec3637612.png)

# Steps to reproduce
1. This [video file](https://www.youtube.com/watch?v=QJ0P9GUr4pc&list=PL1qClmSwVqFWhwPaBGc2wesKZylFvlj2N&index=2), downloaded
2. Subs file added with a delay of +5000ms
3. Input - Ctrl+a
4. Input - K
5. Select word
6. Input - Enter, no definitions found
7. Input - f

**Comment by Ben-Kerman** [comment]
I can't reproduce, and I don't know how it could happen either unless the subtitle line doesn't have a start time for some reason. Are you using 1.1 or the latest commit? Does this happen consistently and with different lines as well?

Could you send me the subtitle file?

**Comment by pndyjack** [comment]
Yes, I'm using 1.1. I tried with another line with a target word that has a definition, and got the same error.
Here's the [subtitle file](https://drive.google.com/file/d/1fM_GFuwErmnzVSMdbZQbet0LbmwUgfD6/view?usp=sharing)

**Comment by Ben-Kerman** [comment]
It's an issue with the subs. The last line has an invalid end time (`00:00:00,000`), which causes mpv to return nil/null for *all* sub start/end times (no idea why, probably a bug in mpv). If you edit the last sub so its end time is after its start time it should work again

**Comment by Ben-Kerman** [comment]
I added a warning with 675470c, that should be enough for now unless it becomes a frequent problem
